# Generated by Django 5.2.12 on 2026-07-18 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_disbursement_received_at_disbursement_received_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='payment_scheme',
            field=models.CharField(choices=[('spot_cash', 'Spot Cash'), ('installment', 'Installment')], max_length=25),
        ),
    ]
