# Generated by Django 5.2.12 on 2026-03-15 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_assigned_at_customuser_assigned_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='preferred_amenities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('broker', 'Broker'), ('staff', 'Staff'), ('property_owner', 'Property Owner'), ('sale_assistant', 'Sale Assistant'), ('client', 'Client')], default='client', max_length=20),
        ),
    ]
