# Generated by Django 5.2.12 on 2026-03-15 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userpreference_preferred_amenities_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('listing_submitted', 'Listing Submitted for Approval'), ('listing_approved', 'Listing Approved'), ('listing_rejected', 'Listing Rejected'), ('listing_flagged', 'Listing Flagged for Review'), ('listing_sold', 'Listing Marked as Sold'), ('reservation_created', 'New Reservation'), ('reservation_approved', 'Reservation Approved'), ('reservation_rejected', 'Reservation Rejected'), ('reservation_cancelled', 'Reservation Cancelled'), ('appointment_created', 'New Appointment Request'), ('appointment_confirmed', 'Appointment Confirmed'), ('appointment_cancelled', 'Appointment Cancelled'), ('sale_created', 'New Sale Created'), ('sale_approved', 'Sale Approved'), ('sale_verified', 'Sale Verified'), ('disbursement_approved', 'Disbursement Approved'), ('disbursement_pending', 'Payment Ready for Receipt'), ('disbursement_completed', 'Disbursement Completed'), ('document_uploaded', 'Document Uploaded'), ('document_approved', 'Document Approved'), ('document_rejected', 'Document Rejected'), ('task_assigned', 'Task Assigned to You'), ('account_disabled', 'Account Disabled'), ('account_enabled', 'Account Enabled'), ('role_assigned', 'Role Assigned'), ('general', 'General Notification')], default='general', max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('link', models.CharField(blank=True, max_length=500, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
