# Generated by Django 5.2.12 on 2026-04-11 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='listing_type',
            field=models.CharField(blank=True, choices=[('for_sale', 'For Sale'), ('for_rent', 'For Rent'), ('any', 'Any')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='preferred_contact',
            field=models.CharField(blank=True, choices=[('email', 'Email'), ('phone', 'Phone / Viber'), ('whatsapp', 'WhatsApp'), ('any', 'Any')], default='any', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='property_type',
            field=models.CharField(blank=True, choices=[('house', 'House'), ('lot', 'Lot'), ('condo', 'Condominium'), ('apartment', 'Apartment'), ('commercial', 'Commercial'), ('any', 'Any Type')], max_length=20, null=True),
        ),
    ]
