# Generated by Django 6.0.4 on 2026-04-20 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_contactmessage_city_contactmessage_listing_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('listing_submitted', 'Listing Submitted for Approval'), ('listing_approved', 'Listing Approved'), ('listing_rejected', 'Listing Rejected'), ('listing_flagged', 'Listing Flagged for Review'), ('listing_sold', 'Listing Marked as Sold'), ('reservation_created', 'New Reservation'), ('reservation_approved', 'Reservation Approved'), ('reservation_rejected', 'Reservation Rejected'), ('reservation_cancelled', 'Reservation Cancelled'), ('appointment_created', 'New Appointment Request'), ('appointment_confirmed', 'Appointment Confirmed'), ('appointment_cancelled', 'Appointment Cancelled'), ('sale_created', 'New Sale Created'), ('sale_approved', 'Sale Approved'), ('sale_verified', 'Sale Verified'), ('disbursement_approved', 'Disbursement Approved'), ('disbursement_pending', 'Payment Ready for Receipt'), ('disbursement_completed', 'Disbursement Completed'), ('document_uploaded', 'Document Uploaded'), ('document_approved', 'Document Approved'), ('document_rejected', 'Document Rejected'), ('task_assigned', 'Task Assigned to You'), ('account_disabled', 'Account Disabled'), ('account_enabled', 'Account Enabled'), ('role_assigned', 'Role Assigned'), ('favorite_unavailable', 'Favorite Property Unavailable'), ('favorite_updated', 'Favorite Property Updated'), ('general', 'General Notification')], default='general', max_length=30),
        ),
    ]
