# Generated by Django 6.0.4 on 2026-04-20 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertypreference',
            name='preferred_amenities',
            field=models.TextField(blank=True, default='', help_text='Free-form desired amenities (e.g., Swimming Pool, Garden, Garage)'),
        ),
    ]
