# Generated by Django 6.0.4 on 2026-04-20 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0002_propertypreference_preferred_amenities'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertypreference',
            name='submitted_at',
            field=models.DateTimeField(blank=True, help_text='When the preferences were submitted to the office', null=True),
        ),
        migrations.AddField(
            model_name='propertypreference',
            name='submitted_to_office',
            field=models.BooleanField(default=False, help_text='Whether preferences were formally submitted to the office'),
        ),
    ]
