# Generated by Django 5.2.12 on 2026-03-15 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
        ('reservations', '0001_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('title', 'Transfer Certificate of Title (TCT)'), ('tax_declaration', 'Tax Declaration'), ('deed_of_sale', 'Deed of Sale'), ('contract_to_sell', 'Contract to Sell'), ('special_power_of_attorney', 'Special Power of Attorney'), ('reservation_agreement', 'Reservation Agreement'), ('payment_receipt', 'Payment Receipt'), ('official_receipt', 'Official Receipt'), ('acknowledgement_receipt', 'Acknowledgement Receipt'), ('valid_id', 'Valid ID'), ('proof_of_income', 'Proof of Income'), ('bank_statement', 'Bank Statement'), ('marriage_certificate', 'Marriage Certificate'), ('birth_certificate', 'Birth Certificate'), ('other', 'Other')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='documents/%Y/%m/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('is_confidential', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='listings.property')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='reservations.reservation')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_documents', to=settings.AUTH_USER_MODEL)),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='sales.sale')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('title', 'Transfer Certificate of Title (TCT)'), ('tax_declaration', 'Tax Declaration'), ('deed_of_sale', 'Deed of Sale'), ('contract_to_sell', 'Contract to Sell'), ('special_power_of_attorney', 'Special Power of Attorney'), ('reservation_agreement', 'Reservation Agreement'), ('payment_receipt', 'Payment Receipt'), ('official_receipt', 'Official Receipt'), ('acknowledgement_receipt', 'Acknowledgement Receipt'), ('valid_id', 'Valid ID'), ('proof_of_income', 'Proof of Income'), ('bank_statement', 'Bank Statement'), ('marriage_certificate', 'Marriage Certificate'), ('birth_certificate', 'Birth Certificate'), ('other', 'Other')], max_length=30)),
                ('is_required', models.BooleanField(default=True)),
                ('is_submitted', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_checklists', to='sales.sale')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='documents.document')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
    ]
