# Generated by Django 5.2.12 on 2026-04-19 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_propertytag_remove_property_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='listing_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('flagged', 'Flagged for Review'), ('approved', 'Approved / For Sale'), ('reserved', 'Reserved'), ('rejected', 'Rejected'), ('sold', 'Sold'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
    ]
