# Generated by Django 6.0.4 on 2026-04-20 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_property_listing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('house', 'House'), ('lot', 'Lot'), ('house_and_lot', 'House and Lot'), ('condo', 'Condominium'), ('commercial', 'Commercial'), ('apartment', 'Apartment'), ('warehouse', 'Warehouse')], max_length=20),
        ),
    ]
