# Generated by Django 6.0.4 on 2026-04-20 06:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_property_is_featured_alter_property_property_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='sale_assistant',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'sale_assistant'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_properties', to=settings.AUTH_USER_MODEL),
        ),
    ]
