# Generated by Django 5.2.12 on 2026-03-15 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('sales_summary', 'Sales Summary Report'), ('sales_by_property', 'Sales by Property Report'), ('sales_by_agent', 'Sales by Agent Report'), ('sales_by_period', 'Sales by Period Report'), ('reservation_summary', 'Reservation Summary Report'), ('reservation_status', 'Reservation Status Report'), ('property_inventory', 'Property Inventory Report'), ('property_status', 'Property Status Report'), ('disbursement_summary', 'Disbursement Summary Report'), ('commission_report', 'Commission Report'), ('payment_collection', 'Payment Collection Report'), ('document_status', 'Document Status Report'), ('document_checklist', 'Document Checklist Report'), ('custom', 'Custom Report')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV')], default='pdf', max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/%Y/%m/')),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('sales_summary', 'Sales Summary Report'), ('sales_by_property', 'Sales by Property Report'), ('sales_by_agent', 'Sales by Agent Report'), ('sales_by_period', 'Sales by Period Report'), ('reservation_summary', 'Reservation Summary Report'), ('reservation_status', 'Reservation Status Report'), ('property_inventory', 'Property Inventory Report'), ('property_status', 'Property Status Report'), ('disbursement_summary', 'Disbursement Summary Report'), ('commission_report', 'Commission Report'), ('payment_collection', 'Payment Collection Report'), ('document_status', 'Document Status Report'), ('document_checklist', 'Document Checklist Report'), ('custom', 'Custom Report')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annually', 'Annually')], max_length=20)),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV')], default='pdf', max_length=10)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('next_run', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_reports', to=settings.AUTH_USER_MODEL)),
                ('recipients', models.ManyToManyField(blank=True, related_name='report_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
