# Generated by Django 5.2.12 on 2026-03-15 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='turnaround_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('sales_summary', 'Sales Summary Report'), ('sales_by_property', 'Sales by Property Report'), ('sales_by_agent', 'Sales by Agent/Sale Assistant Report'), ('sales_turnaround', 'Sales Turnaround Report'), ('reservation_summary', 'Reservation Summary Report'), ('property_inventory', 'Property Inventory Report'), ('property_status', 'Property Status Report'), ('disbursement_summary', 'Disbursement Summary Report'), ('commission_report', 'Commission Report'), ('payment_collection', 'Payment Collection Report'), ('document_status', 'Document Status Report'), ('total_listings', 'Total Listings Overview'), ('user_summary', 'User Summary Report'), ('custom', 'Custom Report')], max_length=30),
        ),
        migrations.AlterField(
            model_name='reportschedule',
            name='report_type',
            field=models.CharField(choices=[('sales_summary', 'Sales Summary Report'), ('sales_by_property', 'Sales by Property Report'), ('sales_by_agent', 'Sales by Agent/Sale Assistant Report'), ('sales_turnaround', 'Sales Turnaround Report'), ('reservation_summary', 'Reservation Summary Report'), ('property_inventory', 'Property Inventory Report'), ('property_status', 'Property Status Report'), ('disbursement_summary', 'Disbursement Summary Report'), ('commission_report', 'Commission Report'), ('payment_collection', 'Payment Collection Report'), ('document_status', 'Document Status Report'), ('total_listings', 'Total Listings Overview'), ('user_summary', 'User Summary Report'), ('custom', 'Custom Report')], max_length=30),
        ),
    ]
