# Generated by Django 6.0.4 on 2026-04-20 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_report_report_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('sales_summary', 'Sales Summary Report'), ('sales_by_property', 'Sales by Property Report'), ('sales_by_agent', 'Sales by Agent/Sale Assistant Report'), ('sales_turnaround', 'Sales Turnaround Report'), ('monthly_sales', 'Monthly Sales Report'), ('reservation_summary', 'Reservation Summary Report'), ('property_inventory', 'Property Inventory Report'), ('property_status', 'Property Status Report'), ('disbursement_summary', 'Disbursement Summary Report'), ('commission_report', 'Commission Report'), ('payment_collection', 'Payment Collection Report'), ('document_status', 'Document Status Report'), ('listing_documents', 'Listing Documents Report'), ('total_listings', 'Total Listings Overview'), ('total_inquiries', 'Total Inquiries Report'), ('user_summary', 'User Summary Report'), ('custom', 'Custom Report')], max_length=30),
        ),
        migrations.AlterField(
            model_name='reportschedule',
            name='report_type',
            field=models.CharField(choices=[('sales_summary', 'Sales Summary Report'), ('sales_by_property', 'Sales by Property Report'), ('sales_by_agent', 'Sales by Agent/Sale Assistant Report'), ('sales_turnaround', 'Sales Turnaround Report'), ('monthly_sales', 'Monthly Sales Report'), ('reservation_summary', 'Reservation Summary Report'), ('property_inventory', 'Property Inventory Report'), ('property_status', 'Property Status Report'), ('disbursement_summary', 'Disbursement Summary Report'), ('commission_report', 'Commission Report'), ('payment_collection', 'Payment Collection Report'), ('document_status', 'Document Status Report'), ('listing_documents', 'Listing Documents Report'), ('total_listings', 'Total Listings Overview'), ('total_inquiries', 'Total Inquiries Report'), ('user_summary', 'User Summary Report'), ('custom', 'Custom Report')], max_length=30),
        ),
    ]
