# Generated by Django 5.2.12 on 2026-07-18 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_alter_report_report_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='format',
            field=models.CharField(choices=[('pdf', 'PDF')], default='pdf', max_length=10),
        ),
        migrations.AlterField(
            model_name='reportschedule',
            name='format',
            field=models.CharField(choices=[('pdf', 'PDF')], default='pdf', max_length=10),
        ),
    ]
